/* Automatic generated by './build/bin/build-entry.js' */

import Pagination from '../packages/pagination';


const components = [
  Pagination,
  
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });


};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  install,
  Pagination,
};
